import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col">
          <Navbar />
          <main className="flex-grow w-full"> {/* Full width */}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
